Konstantinov
FastSense/rosbot-ros2 pull request #9
Opened 2021-07-06 12:13 UTC by CI314X

Здесь история: https://github.com/FastSense/rosbot-ros2/issues/7

2021-07-06 12:37 UTC, KostyaYamshanov requested changes
На мой взгляд, все хорошо, можно подправить мелкие моменты и мержить. Ждем что сажут остальные

2021-07-06 12:37 UTC, KostyaYamshanov commented on rosbot_controller/rosbot_controller/path_follower.py
> +        self.odom_frame = "odom"
может сделать как параметр, назовем parent_frame (это может быть map или еще какой)

2021-07-06 12:37 UTC, KostyaYamshanov commented on rosbot_controller/rosbot_controller/path_publisher.py
> +    def IsValidTrajType(self):
методы обычно называют строчными, из через "_", будет типа is_valid_traj_type

2021-07-06 12:37 UTC, KostyaYamshanov commented on rosbot_controller/rosbot_controller/path_publisher.py
> +            zz = list(Rotation.from_euler(
лучше выбрать более явное имя, zz не очень информативно ) (goal_quaternion, goal_orient, можно как-то так)

2021-07-06 13:06 UTC, urock requested changes

2021-07-06 13:06 UTC, urock commented on rosbot_controller/rosbot_controller/path_follower.py
> +        self.path_sub
self.path_sub

это что?

2021-07-06 13:06 UTC, urock commented on rosbot_controller/rosbot_controller/path_follower.py
> +
а почему убрали вычисление ошибки следования? а path_index оставили, хотя path_index как раз для этого и использовалась

2021-07-06 13:06 UTC, urock commented on rosbot_controller/rosbot_controller/rosbot_2D.py
> +        return dist < 0.2
тут константу поменять на 
self.xy_margin_squared

2021-07-06 13:08 UTC, CI314X commented on rosbot_controller/rosbot_controller/path_follower.py
> +        self.path_sub
Так по туториалу рекомендуется писать во избежании неких проблем)

2021-07-06 13:11 UTC, CI314X commented on rosbot_controller/rosbot_controller/path_publisher.py
> +            zz = list(Rotation.from_euler(
done

2021-07-06 13:11 UTC, CI314X commented on rosbot_controller/rosbot_controller/path_publisher.py
> +    def IsValidTrajType(self):
done

2021-07-06 13:12 UTC, CI314X commented on rosbot_controller/rosbot_controller/path_follower.py
> +        self.odom_frame = "odom"
done

2021-07-06 13:25 UTC, CI314X commented on rosbot_controller/rosbot_controller/path_follower.py
> +
Костя говорит, вы ее не использовали, так что непонятно, стоит ли её добавлять?

2021-07-06 13:43 UTC, CI314X commented on rosbot_controller/rosbot_controller/path_follower.py
> +
добавил

2021-07-06 14:41 UTC, KostyaYamshanov approved these changes

2021-07-08 08:45 UTC, KostyaYamshanov approved these changes
Ну у меня вопросов нет, на мой взгляд, все хорошо

Но вроде как мы должны хранить модели в репозитоиях, поэтому я бы удалил 
nets/rosbot_gazebo9_2d_model.onnx

2021-07-08 08:45 UTC, KostyaYamshanov commented on rosbot_controller/rosbot_controller/model_runner.py
> +        elif self.model_type == "nn":
давай 'nn' заменим, на что-то более понятное ) "nn_model" хотя бы

2021-07-08 08:50 UTC, CI314X commented on rosbot_controller/rosbot_controller/model_runner.py
> +        elif self.model_type == "nn":
done

2021-09-14 15:12 UTC, KostyaYamshanov approved these changes

2021-09-14 16:00 UTC, urock approved these changes

2021-09-16 09:08 UTC, merged